---
all:
  children:
    rhel:
      hosts:
        rhel-01:
          ansible_host: lightspeed-101-controller # Update this to your target host.
  vars:
    ansible_ssh_private_key_file: "~/.ssh/instruqt_lab" # Update this to your target host.
    ansible_user: rhel # Update this to your target host.
    ansible_host_key_checking: false
